/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Sentiment Search API
 * Core API for handling user searches and delegating tracking tasks.
 * OpenAPI spec version: 1.0.0
 */
export type PostInternalTrackBody = {
  /** The unique correlation ID for this entire aggregation job. */
  scanJobId?: string;
  /** The ticker symbol (e.g., TSLA). */
  stockId: string;
  /**
   * The interval in seconds at which the tracker should check for new articles. For example, if set to 60, the tracker will look for new articles every minute.
   * @minimum 1
   */
  interval: number;
  /**
   * Time-to-live in seconds for this tracking job. After this time, the tracker should stop looking for new articles and clean up any resources.
   * @minimum 1
   */
  ttl: number;
};

export type PostInternalTrack200 = {
  scanJobId: string;
  /**
   * The number of articles the tracker found and pushed to RabbitMQ. Is only filled if the ttl if set to 0, indicating that it is a one-time scrape command.
   * @minimum 0
   */
  expectedArticles: number;
} | null;

/**
 * @summary Command the Tracking Service to track a stock.
 */
export type postInternalTrackResponse200 = {
  data: PostInternalTrack200;
  status: 200;
};

export type postInternalTrackResponseSuccess = postInternalTrackResponse200 & {
  headers: Headers;
};
export type postInternalTrackResponse = postInternalTrackResponseSuccess;

export const getPostInternalTrackUrl = () => {
  return `/internal/track`;
};

export const postInternalTrack = async (
  postInternalTrackBody: PostInternalTrackBody,
  options?: RequestInit
): Promise<postInternalTrackResponse> => {
  const res = await fetch(getPostInternalTrackUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(postInternalTrackBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postInternalTrackResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postInternalTrackResponse;
};
