/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Sentiment Search API
 * Core API for handling user searches and delegating tracking tasks.
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiSearch200SourcesItem } from './getApiSearch200SourcesItem.gen';
import type { GetApiSearch200Stock } from './getApiSearch200Stock.gen';

export type GetApiSearch200 = {
  stock: GetApiSearch200Stock;
  sources: GetApiSearch200SourcesItem[];
  /**
     * @minimum -1
     * @maximum 1
     */
  score: number;
};
