/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Sentiment Search API
 * Core API for handling user searches and delegating tracking tasks.
 * OpenAPI spec version: 1.0.0
 */

export type GetApiSearchParams = {
/**
 * The stock name or topic to search.
 */
query: string;
};
