import { z } from "zod";

export default z.object({
  scanJobId: z.string().uuid().optional(),
  stockId: z.string(),
  score: z
    .number()
    .gte(-1)
    .lte(1)
    .describe("The sentiment score generated by FinBERT."),
  snippet: z.string(),
  url: z.string().url(),
});
