/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Sentiment Search API
 * Core API for handling user searches and delegating tracking tasks.
 * OpenAPI spec version: 1.0.0
 */

export type PostInternalTrackBody = {
  /** The unique correlation ID for this entire aggregation job. */
  scanJobId?: string;
  /** The ticker symbol (e.g., TSLA). */
  stockId: string;
  /**
     * The interval in seconds at which the tracker should check for new articles. For example, if set to 60, the tracker will look for new articles every minute.
     * @minimum 1
     */
  interval: number;
  /**
     * Time-to-live in seconds for this tracking job. After this time, the tracker should stop looking for new articles and clean up any resources.
     * @minimum 1
     */
  ttl: number;
};
