/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Sentiment Search API
 * Core API for handling user searches and delegating tracking tasks.
 * OpenAPI spec version: 1.0.0
 */

export type PostInternalTrack200 = {
  scanJobId: string;
  /**
     * The number of articles the tracker found and pushed to RabbitMQ. Is only filled if the ttl if set to 0, indicating that it is a one-time scrape command.
     * @minimum 0
     */
  expectedArticles: number;
} | null;
