/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Sentiment Search API
 * Core API for handling user searches and delegating tracking tasks.
 * OpenAPI spec version: 1.0.0
 */
import type {
  PostInternalTrack200,
  PostInternalTrackBody
} from '../dtos';


/**
 * @summary Command the Tracking Service to track a stock.
 */
export type postInternalTrackResponse200 = {
  data: PostInternalTrack200
  status: 200
}

export type postInternalTrackResponseSuccess = (postInternalTrackResponse200) & {
  headers: Headers;
};
;

export type postInternalTrackResponse = (postInternalTrackResponseSuccess)

export const getPostInternalTrackUrl = () => {




  return `/internal/track`
}

export const postInternalTrack = async (postInternalTrackBody: PostInternalTrackBody, options?: RequestInit): Promise<postInternalTrackResponse> => {

  const res = await fetch(getPostInternalTrackUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postInternalTrackBody,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postInternalTrackResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postInternalTrackResponse
}



