/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Sentiment Search API
 * Core API for handling user searches and delegating tracking tasks.
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetApiSearch200,
  GetApiSearchParams
} from './dtos';


interface TypedResponse<T> extends Response {
  json(): Promise<T>;
}


export type getApiSearchResponse200 = {
  stream: TypedResponse<GetApiSearch200>
  status: 200
}

export type getApiSearchResponseSuccess = (getApiSearchResponse200) & {
  headers: Headers;
};
;

export type getApiSearchResponse = (getApiSearchResponseSuccess)

export const getGetApiSearchUrl = (params: GetApiSearchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/search?${stringifiedParams}` : `/api/search`
}

/**
 * @summary Search for a stock's sentiment (ndJSON Stream)
 */
export const getApiSearch = async (params: GetApiSearchParams, options?: RequestInit): Promise<getApiSearchResponse> => {

    const stream = await fetch(getGetApiSearchUrl(params),
  {
    ...options,
    method: 'GET',
    headers: { Accept: 'application/x-ndjson', ...options?.headers }

  }
);

  return { status: stream.status, stream, headers: stream.headers } as getApiSearchResponse
  }



