/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Sentiment Search API
 * Core API for handling user searches and delegating tracking tasks.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * @summary Search for a stock's sentiment (ndJSON Stream)
 */
export const GetApiSearchQueryParams = zod.object({
  "query": zod.string().describe('The stock name or topic to search.')
})
