name: Build Core

on:
  pull_request:
    branches-ignore:
      - main
    paths:
      - "core/**"
      - ".github/workflows/build.core.yml"
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: core

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          package_json_file: core/package.json

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"
          cache-dependency-path: core/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Check formatting
        run: pnpm run format:check

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build
