name: Package Tracker

on:
  pull_request:
    branches:
      - main
    paths:
      - "tracker/**"
      - ".github/workflows/build.tracker.yml"
      - ".github/workflows/package.tracker.yml"
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: 'latest'

jobs:
  build:
    uses: ./.github/workflows/build.tracker.yml

  package:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: tracker

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          package_json_file: tracker/package.json

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"
          cache-dependency-path: tracker/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Set package.json version
        if: ${{ inputs.version && inputs.version != 'latest' }}
        run: pnpm version ${{ inputs.version }} --no-git-tag-version --allow-same-version

      - name: Build Docker Image
        run: docker build -t tracker:${{ inputs.version || 'latest' }} .

      - name: Save Docker Image
        run: docker save tracker:${{ inputs.version || 'latest' }} -o tracker-${{ inputs.version || 'latest' }}.tar

      - name: Upload Docker Image
        uses: actions/upload-artifact@v6
        with:
          name: docker-image-tracker-${{ inputs.version || 'latest' }}
          path: tracker/tracker-${{ inputs.version || 'latest' }}.tar
          if-no-files-found: error
